# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Base16 Monokai - alacritty color config
# Wimer Hazenberg (http://www.monokai.nl)
colors:
  # Default colors
  primary:
    background: '0x272822'
    foreground: '0xf8f8f2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x272822'
    cursor: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x272822'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf8f8f2'

  # Bright colors
  bright:
    black:   '0x75715e'
    red:     '0xfd971f'
    green:   '0x383830'
    yellow:  '0x49483e'
    blue:    '0xa59f85'
    magenta: '0xf5f4f1'
    cyan:    '0xcc6633'
    white:   '0xf9f8f5'

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 12


window:
  dimensions:
   columns: 132
   lines: 32

shell:
 program: /usr/bin/fish
 args:
    - -l
    - -c
    - "tmux attach || tmux"